language: csharp
mono: none
dotnet: 2.1.300
script:
- dotnet build src/Domain
- dotnet build src/Infrastructure
- dotnet build src/Locations.API
- dotnet build src/Places.API
- dotnet build src/Application
- dotnet build tests/Locations.API.Tests
- dotnet test tests/Locations.API.Tests